require('dotenv').config();
const express = require('express');
const cors = require('cors');
const TelegramBot = require('node-telegram-bot-api');
const crypto = require('crypto');
const db = require('./db');

const app = express();
const PORT = process.env.PORT || 3000;

// Enable CORS and JSON parsing
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// In-memory store for valid keys generated by the bot
const validKeys = new Map();

// Whitelist the real key for proxy features
validKeys.set('LOVABLE-Q9E8-H6AV-EEVV-GAXJ', {
  expiresAt: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString()
});
// In-memory activated sessions store
const activeSessions = new Map();

// Helper: Generate 12-character formatted key: LOVE-XXXX-XXXX
function generateLicenseKey() {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let randomPart = '';
  for (let i = 0; i < 8; i++) {
    const randomIndex = crypto.randomInt(0, chars.length);
    randomPart += chars[randomIndex];
  }
  return `LOVE-${randomPart.slice(0, 4)}-${randomPart.slice(4, 8)}`;
}

// Helper: Format expiration date
function getExpiryDate(days) {
  const date = new Date();
  date.setDate(date.getDate() + parseInt(days, 10));
  return date.toISOString().split('T')[0];
}

// Validation Handler logic (supports /api/validate, /validate, and root fallback)
function handleValidate(req, res) {
  const body = req.body || {};
  const license_key = body.license_key || body.licenseKey || body.key || body.ql_license_key;
  const device_id = body.device_id || body.deviceId || 'device_default';
  const session_id = body.session_id || body.sessionId;

  console.log(`[Validation Request] Path: ${req.path}, Key: "${license_key}", Device: "${device_id}", Session: "${session_id}"`);

  // Verify the key is in our valid keys map
  if (!validKeys.has(license_key)) {
    return res.status(400).json({
      valid: false,
      status: 'invalid',
      message: 'License not found or invalid key!'
    });
  }

  const keyData = validKeys.get(license_key) || { expires_at: new Date(Date.now() + 365*24*60*60*1000) };

  const activeSessionId = session_id || 'sess_' + crypto.randomBytes(12).toString('hex');
  const now = new Date();
  const expiresAt = new Date(keyData.expires_at).toISOString();

  activeSessions.set(activeSessionId, {
    license_key: license_key || 'LOVE-FREEFLOW-KEY',
    device_id: device_id,
    activated_at: now.toISOString(),
    expires_at: expiresAt
  });

  return res.json({
    // Old extension format
    valid: true,
    status: 'valid',
    message: 'License activated successfully!',
    user_name: 'Lovable Unlimited',
    session_id: activeSessionId,
    expires_at: expiresAt,
    activated_at: now.toISOString(),
    
    // New extension format
    ok: true,
    license_id: 'lic_' + crypto.randomBytes(8).toString('hex'),
    email: 'user@lovable.app',
    license: {
      expires_at: expiresAt,
      created_at: now.toISOString(),
      plan: 'premium',
      status: 'active',
      bound_email: 'user@lovable.app'
    }
  });
}

// Register endpoints
app.post('/api/validate', handleValidate);
app.post('/validate', handleValidate);

// Health check endpoint for Railway & monitoring
app.get('/health', (req, res) => {
  res.json({ status: 'ok', service: 'LOVABLE License Backend', timestamp: new Date().toISOString() });
});

app.get('/', (req, res) => {
  res.send('<h1>LOVABLE License Server & API</h1><p>Status: Active | Endpoint: <code>POST /api/validate</code></p>');
});

// Stub endpoints for extension features (bypassing eklas proxy)
app.post('/api/v1/lovable/session', (req, res) => res.json({ ok: true }));
app.post('/api/v1/lovable/chat', (req, res) => res.json({ ok: true }));
app.post('/api/v1/lovable/approve-plan', (req, res) => res.json({ ok: true }));
app.post('/api/v1/lovable/create-project', (req, res) => res.json({ ok: true }));
app.post('/api/v1/lovable/source-code', (req, res) => res.json({ ok: true }));

// Start Express HTTP Server
app.listen(PORT, '0.0.0.0', () => {
  console.log(`🚀 LOVABLE License API Server running on port ${PORT}`);
});

// Optional Telegram Bot Initialization
const token = process.env.BOT_TOKEN;
const ADMIN_CHAT_ID = process.env.ADMIN_CHAT_ID;

if (token && token !== 'YOUR_TELEGRAM_BOT_TOKEN_HERE') {
  try {
    const bot = new TelegramBot(token, { polling: true });
    console.log('🤖 LOVABLE Telegram License Bot is running...');

    const adminStates = new Map();

    function checkAuth(ctxFromId, chatId) {
      if (chatId.toString() === ADMIN_CHAT_ID) return true;
      const auth = db.isUserAuthorized(ctxFromId);
      return auth.isAuthorized;
    }

    function sendAccessDenied(chatId) {
      bot.sendMessage(chatId, "⛔ <b>Access Denied</b>\n\nYou are not authorized to use this bot. Please contact the administrator for access.", { parse_mode: 'HTML' });
    }

    bot.onText(/\/start/, (msg) => {
      const chatId = msg.chat.id;
      if (!checkAuth(msg.from.id, chatId)) {
        return sendAccessDenied(chatId);
      }
      sendDurationPrompt(bot, chatId, chatId.toString() === ADMIN_CHAT_ID);
    });

    bot.on('message', (msg) => {
      if (msg.text && msg.text.startsWith('/start')) return;

      const chatId = msg.chat.id;
      if (!checkAuth(msg.from.id, chatId)) {
        if (!msg.text?.startsWith('/')) sendAccessDenied(chatId);
        return;
      }

      const text = msg.text;
      
      if (chatId.toString() === ADMIN_CHAT_ID && adminStates.has(chatId)) {
        const state = adminStates.get(chatId);
        if (state.action === 'AWAITING_USER_ADD') {
          const parts = text.split(',');
          if (parts.length === 2) {
            const userId = parts[0].trim();
            const maxKeys = parseInt(parts[1].trim(), 10);
            if (!isNaN(maxKeys)) {
              db.addAuthorizedUser(userId, maxKeys);
              bot.sendMessage(chatId, `✅ Successfully authorized user ${userId} for ${maxKeys} keys/day.`);
            } else {
              bot.sendMessage(chatId, '❌ Invalid format. Please send: UserID, MaxKeys');
            }
          } else {
            bot.sendMessage(chatId, '❌ Invalid format. Please send: UserID, MaxKeys');
          }
          adminStates.delete(chatId);
          return;
        } else if (state.action === 'AWAITING_BULK_KEYS') {
          const keys = text.split(/[\n,]+/).map(k => k.trim()).filter(k => k.length > 0);
          if (keys.length > 0) {
            const added = db.addBulkKeys(state.validity, keys);
            bot.sendMessage(chatId, `✅ Successfully added ${added} keys to the ${state.validity} inventory.`);
          } else {
            bot.sendMessage(chatId, '❌ No valid keys found.');
          }
          adminStates.delete(chatId);
          return;
        }
      }

      if (text && !text.startsWith('/')) {
        const days = parseInt(text, 10);
        if (!isNaN(days) && days > 0) {
          issueKey(bot, chatId, days);
        } else {
          sendDurationPrompt(bot, chatId, chatId.toString() === ADMIN_CHAT_ID);
        }
      }
    });

    bot.on('callback_query', (query) => {
      const chatId = query.message.chat.id;
      const data = query.data;

      if (!checkAuth(query.from.id, chatId)) {
        bot.answerCallbackQuery(query.id, { text: "⛔ Access Denied", show_alert: true });
        return;
      }

      if (data === 'admin_add_user' && chatId.toString() === ADMIN_CHAT_ID) {
        adminStates.set(chatId, { action: 'AWAITING_USER_ADD' });
        bot.sendMessage(chatId, 'Send the user ID and daily limit separated by a comma.\nExample: 123456789, 5');
        bot.answerCallbackQuery(query.id);
        return;
      }

      if (data === 'admin_bulk_upload' && chatId.toString() === ADMIN_CHAT_ID) {
        const options = {
          reply_markup: {
            inline_keyboard: [
              [ { text: '[20m]', callback_data: 'admin_upload:20m' }, { text: '[1d]', callback_data: 'admin_upload:1d' }, { text: '[3d]', callback_data: 'admin_upload:3d' } ],
              [ { text: '[7d]', callback_data: 'admin_upload:7d' }, { text: '[14d]', callback_data: 'admin_upload:14d' }, { text: '[30d]', callback_data: 'admin_upload:30d' } ]
            ]
          }
        };
        bot.sendMessage(chatId, 'Select the validity for the keys you are uploading:', options);
        bot.answerCallbackQuery(query.id);
        return;
      }

      if (data.startsWith('admin_upload:') && chatId.toString() === ADMIN_CHAT_ID) {
        const validity = data.split(':')[1];
        adminStates.set(chatId, { action: 'AWAITING_BULK_KEYS', validity });
        bot.sendMessage(chatId, `Please paste the keys for ${validity} validity (separated by commas or newlines).`);
        bot.answerCallbackQuery(query.id);
        return;
      }

      if (data === 'menu:extension_1') {
        const stock = db.getInventoryStock();
        const inline_keyboard = [];
        let currentRow = [];
        
        for (const [validity, count] of Object.entries(stock)) {
          if (count > 0) {
            currentRow.push({ text: `${validity} (${count} in stock)`, callback_data: `claim_ext:${validity}` });
            if (currentRow.length === 2) {
              inline_keyboard.push(currentRow);
              currentRow = [];
            }
          }
        }
        if (currentRow.length > 0) inline_keyboard.push(currentRow);

        if (inline_keyboard.length === 0) {
          bot.sendMessage(chatId, '📦 <b>Available Extension Keys</b>\n\nCurrently out of stock for all validities.', { parse_mode: 'HTML' });
        } else {
          bot.sendMessage(chatId, '📦 <b>Available Extension Keys</b>\n\nSelect a validity below to generate a key. You can claim up to your daily limit.', {
            parse_mode: 'HTML',
            reply_markup: { inline_keyboard }
          });
        }
        bot.answerCallbackQuery(query.id);
        return;
      }

      if (data.startsWith('claim_ext:')) {
        const validity = data.split(':')[1];
        
        if (!db.canUserClaimToday(query.from.id)) {
          bot.sendMessage(chatId, "🛑 <b>Daily Limit Reached</b>\nYou have exhausted your daily key allowance. Please try again tomorrow.", { parse_mode: 'HTML' });
          bot.answerCallbackQuery(query.id);
          return;
        }

        const keyString = db.dispenseKey(validity, query.from.id);
        if (!keyString) {
          bot.sendMessage(chatId, "❌ Out of stock for this validity.");
          bot.answerCallbackQuery(query.id);
          return;
        }

        db.incrementUserClaim(query.from.id);
        bot.sendMessage(chatId, `🎉 <b>Key Generated Successfully!</b>\n\nValidity: ${validity}\nLicense Key: <code>${keyString}</code>`, { parse_mode: 'HTML' });
        bot.answerCallbackQuery(query.id);
        return;
      }

      if (data.startsWith('duration_')) {
        const days = parseInt(data.replace('duration_', ''), 10);
        bot.answerCallbackQuery(query.id);
        issueKey(bot, chatId, days);
      }
    });
  } catch (err) {
    console.error('Failed to start Telegram Bot:', err.message);
  }
} else {
  console.log('ℹ️ BOT_TOKEN not set or default. Running HTTP API server only.');
}

function sendDurationPrompt(bot, chatId, isAdmin = false) {
  const inline_keyboard = [
    [
      { text: '🧩 Extension 1', callback_data: 'menu:extension_1' }
    ]
  ];

  if (isAdmin) {
    inline_keyboard.push([
      { text: '👥 Add Authorized User', callback_data: 'admin_add_user' },
      { text: '🔑 Bulk Upload Keys', callback_data: 'admin_bulk_upload' }
    ]);
  }

  const options = {
    reply_markup: {
      inline_keyboard
    }
  };
  bot.sendMessage(chatId, '✨ *Welcome to LOVABLE License Generator*\n\nPlease select an option below:', { parse_mode: 'Markdown', ...options });
}

function issueKey(bot, chatId, days) {
  const licenseKey = generateLicenseKey();
  const expiry = getExpiryDate(days);

  validKeys.set(licenseKey, {
    duration: days,
    expires_at: expiry
  });

  const message = `🔑 *LOVABLE License Key Generated!*\n\n` +
                  `*License Key:* \`${licenseKey}\`\n` +
                  `*Duration:* ${days} Days\n` +
                  `*Expires On:* ${expiry}\n\n` +
                  `_Tap to copy the license key above._`;

  bot.sendMessage(chatId, message, { parse_mode: 'Markdown' });
}

module.exports = {
  generateLicenseKey,
  getExpiryDate
};
